name: currency_converter
description: "Currency converter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  flag: ^7.0.2
  flutter_launcher_icons: ^0.14.4
  get_it: ^9.2.0
  injectable: ^2.7.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.11.1
  build_runner: ^2.10.4
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
